# Generated by Django 3.2.9 on 2021-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('standerd', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='student_images/')),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('previous_school', models.CharField(max_length=200)),
                ('previous_result', models.CharField(max_length=200)),
            ],
        ),
    ]
